#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/param_googlenet.bin ../host/model/googlenet_q_1 ../host/test_images/data_googlenet.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/resnet50-20190409/param.bin ../host/model/resnet50_qq ../host/model/resnet50-20190409/data.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/param_googlenet.bin ../host/model/googlenet_q_1 ../host/test_images/googlenet_data_label_0.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/resnet50-20190409/param.bin ../host/model/resnet50_qq ../host/test_images/resnet50_data_label_0.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/ResNet50-inq/param.bin ../host/model/resnet50_inq_qq ../host/model/ResNet50-inq/data.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/ResNet50-inq/param.bin ../host/model/resnet50_inq_qq ../host/model/resnet50_data_label_100.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/resnet50-20190409/param.bin ../host/model/resnet50_qq ../host/model/resnet50_data_label_100.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/param_googlenet.bin ../host/model/googlenet_q_1 ../host/test_images/data_googlenet.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_q_1 ../host/model/googlenet/data.bin ../host/model/googlenet/pool1_3x3_s2.bin 1

#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_q_1 ../host/model/googlenet/data.bin ../host/model/googlenet/loss3_classifier.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/resnet50/param.bin ../host/model/resnet50_qq ../host/model/resnet50/data.bin ../host/model/resnet50/fc1000.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/resnet50_pruned/param.bin ../host/model/resnet50_inq_qq ../host/model/resnet50_pruned/data.bin ../host/model/resnet50_pruned/fc1000.bin 1

#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/conv1_7x7_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/pool1_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/conv2_3x3_reduce.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/pool2_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/loss3_classifier.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/inception_3a_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/pool3_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd/inception_5b_output.bin 1

#./bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_q_1 ../host/model/googlenet/data.bin ../host/model/googlenet/loss3_classifier.bin 1

#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/conv1_7x7_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/pool1_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/conv2_3x3_reduce.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/inception_3a_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/pool3_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/inception_4a_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/inception_4b_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/inception_4d_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/pool4_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/inception_5b_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float/loss3_classifier.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/loss3_classifier.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/googlenet_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_Q ../host/model/googlenet_winograd/data.bin ../host/model/googlenet_winograd/inception_3a_1x1.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/googlenet_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_Q ../host/model/googlenet_winograd/data.bin ../host/model/googlenet_winograd/loss3_classifier.bin 1
./bin/host ../host/model/googlenet_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_Q ../host/model/googlenet_winograd/data.bin ../host/model/googlenet_winograd/loss3_classifier.bin 1
#./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/loss3_classifier.bin 32
#./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/loss3_classifier.bin 1
#nohup ./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/conv1_7x7_s2.bin 1 &
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/conv1_7x7_s2.bin 1 &
#CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/inception_5b_output.bin 1
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/pool1_3x3_s2.bin 1 &
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/pool1_3x3_s2.bin 1
#./bin/host ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/data.bin ../host/model/GoogLeNet_F_5_3_winograd_float_20191011/pool1_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/pool1_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/pool1_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_3a_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4e_1x1.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4e_3x3_reduce.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4e_5x5_reduce.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4e_5x5.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4e_pool.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4e_3x3.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4e_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/pool4_3x3_s2.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_4d_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_5a_output.bin 1
#CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1 ./bin/host ../host/model/GoogLeNet_F_5_3_winograd/GoogLeNetWinogradParam.bin ../host/model/googlenet_q_1 ../host/model/GoogLeNet/data.bin ../host/model/GoogLeNet/inception_5b_output.bin 1
