#./bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_Q ../host/test_images/googlenet_data_label_391.bin ../host/model/googlenet/loss3_classifier.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_Q ../host/test_images/googlenet_data_label_391.bin ../host/verify/googlenet_fc1000_label_391.bin 3
#./bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_Q ../host/test_images/googlenet_data_label_391.bin ../host/verify/googlenet_fc1000_label_391.bin 16
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/resnet50/param.bin ../host/model/resnet50_Q ../host/test_images/resnet50_data_label_100.bin ../host/verify/resnet50_fc1000_label_100.bin 2
#./bin/host ../host/model/resnet50/param.bin ../host/model/resnet50_Q ../host/test_images/resnet50_data_label_100.bin ../host/verify/resnet50_fc1000_label_100.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/resnet50_pruned/param.bin ../host/model/resnet50_pruned_Q ../host/model/resnet50_pruned/data.bin ../host/model/resnet50_pruned/fc1000.bin 2
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/pool1.bin 1 &
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res2a_branch1-scale.bin 1 &
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res2a_branch1-scale.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res2a_branch2a-scale.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res2a_branch2b-relu.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res2a.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res3a_branch1.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res2a_branch2c-scale.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res2c.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res3a_branch1-scale.bin 1 
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res3a_branch1-scale.bin 1 &
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res3a_branch1-scale.bin 1 
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res3a_branch2a-scale.bin 1 
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res3a_branch2b-scale.bin 1 &
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res3d.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res4a.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res4f.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res5a.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res5b.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res5c.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res5c_branch2b-scale.bin 1
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/res5c_branch2c-scale.bin 1 &
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/fc1000.bin 1
# env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/fpgamodel.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/fc1000.bin 1
# env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl/data.bin ../host/model/pytorch_4bit_quantization/fc1000.bin 1
# env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl/data.bin ../host/model/pytorch_4bit_quantization/fc1000.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/pool1.bin 1

#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2a_branch1_bn.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2a_branch1_bn.bin 1 
#./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2a_branch1_bn.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2a_branch1_bn.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2a_branch2a_relu.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2a_branch2b_relu.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2a_relu.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2b_branch2a_relu.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2b_branch2b_relu.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2b_relu.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res2c_branch2a_relu.bin 1
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res3c_branch2b_relu.bin 1 #layer 20
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res4b_branch2b_relu.bin 1 #layer 30
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res5c_relu.bin 1 #layer 53
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res5c_branch2b_relu.bin 1 #layer 52
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res5c_branch2a_relu.bin 1 #layer 51
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res5b_relu.bin 1 #layer 50
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/pool5.bin 1 #layer ipool 54
env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/fc1000.bin 1 #layer fc1000
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/fc1000.bin 50000 #imagenet test
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/fc1000.bin 50000 #imagenet test
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/fc1000.bin 1 #imagenet test
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/fc1000.bin 1 & #imagenet test
#env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 gdb --args ./bin/host ../host/model/pytorch_4bit_quantization/Param.bin ../host/model/pytorch_4bit_scale/Scale.bin ../host/model/pytorch_4bit_orl_data/data.bin ../host/model/pytorch_4bit_quantization/res5c_branch2b_relu.bin 1 //layer 52
# nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/fpgamodel.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/fc1000.bin 1 &
#nohup env CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1 ./bin/host ../host/model/pytorch_resnet50/param.bin ../host/model/pytorch_resnet50_q ../host/model/pytorch_resnet50/data.bin ../host/model/pytorch_resnet50/fc1000.bin 1 &
#./bin/host ../host/model/resnet50_pruned/param.bin ../host/model/resnet50_pruned_Q ../host/model/resnet50_pruned/data.bin ../host/model/resnet50_pruned/fc1000.bin 16
